This program creates a "try...catch" to catch errors and execute codes to handle those errors.

We will test the following:
 * y = l(-2)
 * y = l(2)
 
The output is attached.
